apiVersion: v1
kind: Secret
metadata:
  name: rhythm-secret
data:
  token: TVRBME1EWXdNVGt6TmpNNU5qZ3hNak00T1EuR082RFN6LnVJQnRWNnZPVTQzUXV2a1BLV0xEVmh5WklHRmxEYzA5Y3ZkU0VF
  # token: MTA0MDYwMTkzNjM5NjgxMjM4OQ.GO6DSz.uIBtV6vOU43QuvkPKWLDVhyZIGFlDc09cvdSEE